image: mcr.microsoft.com/dotnet/sdk:6.0

options:
  max-time: 15
pipelines:
  default:
    - step:
        name: "Build/Test"
        script:
          - sleep 10
          - dotnet test SP22.P02.Tests.Web
  branches:
    master:
      - step:
          name: "Build/Test/Publish Web"
          script:
            - apt-get update && apt-get install --yes zip
            - sleep 10
            - dotnet test SP22.P02.Tests.Web
            - dotnet publish SP22.P02.Web --output publish
            - cd publish && zip -r web-$BITBUCKET_BUILD_NUMBER.zip .
          artifacts:
            - publish/*.zip
      - step:
          name: "Deploy to Azure"
          deployment: test
          script:
            - pipe: microsoft/azure-web-apps-deploy:1.0.0
              variables:
                AZURE_APP_ID: $AZURE_APP_ID
                AZURE_PASSWORD: $AZURE_PASSWORD
                AZURE_TENANT_ID: $AZURE_TENANT_ID
                AZURE_RESOURCE_GROUP: "sp22-p02-g##"
                AZURE_APP_NAME: "selu383-sp22-p02-g##"
                ZIP_FILE: "publish/web-$BITBUCKET_BUILD_NUMBER.zip"
      - step:
          name: "Check API Health"
          script:
            - curl -s https://selu383-sp22-p02-g##.azurewebsites.net/api/products
            - sleep 10
            - curl -sSf https://selu383-sp22-p02-g##.azurewebsites.net/api/products
